services:

  ########################################
  #                PostgreSQL           #
  ########################################
  postgres:
    image: postgres:latest
    container_name: cfp-postgres
    environment:
      POSTGRES_USER: manoel
      POSTGRES_PASSWORD: manoel
      POSTGRES_DB: callforpapers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  ########################################
  #                Backend               #
  ########################################
  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/callforpapers
      QUARKUS_DATASOURCE_DB_KIND: postgres
      QUARKUS_DATASOURCE_USERNAME: manoel
      QUARKUS_DATASOURCE_PASSWORD: manoel
    depends_on:
      - postgres
    networks:
      - web

  ########################################
  #           Frontend Flutter Web       #
  ########################################
  frontend:
    image: nginx:latest
    container_name: flutter-web
    ports:
      - "8081:80"
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - quarkus
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    driver: bridge